---
title: "testing"
author: "Jenn Havens"
date: "November 26, 2016"
output: html_document
---

```{r}

#ezproxyData <- read.delim("~/2 Jr/Stats/Project/StatsProject/ezproxyData")
onLocation = vector(length = 120686)

for (i in 1:120686) {
  if (substring(ezproxyData$ipAdress[i], 1, 8) == "134.173."){
    loc <- as.numeric(substring(ezproxyData$ipAdress[i], 9, 11))
    if (loc > 31 && loc < 64) {
      onLocation[i] <- "hmc"
    } else if (loc > 63 && loc < 96) {
      onLocation[i] <- "pomona"
    } else if (loc > 95 && loc < 104) {
      onLocation[i] <- "kgi"
    } else if (loc > 111 && loc < 124) {
      onLocation[i] <- "pitzer"
    } else if (loc > 123 && loc < 136) {
      onLocation[i] <- "cuc"
    } else if (loc > 139 && loc < 142) {
      onLocation[i] <- "kecksci"
    } else if (loc > 143 && loc < 160) {
      onLocation[i] <- "scrippscollege"
    } else if (loc > 159 && loc < 192) {
      onLocation[i] <- "cmc"
    } else if (loc > 223 && loc < 240) {
      onLocation[i] <- "cgu"
    } else if (loc > 7 && loc < 16) {
      onLocation[i] <- "ClaremontSSID"
    } else if (loc > 23 && loc < 32) {
      onLocation[i] <- "ClaremontSSID"
    } else if (loc > 191 && loc < 224) {
      onLocation[i] <- "CINE"
    } else if (loc > 243 && loc < 246) {
      onLocation[i] <- "VPNinterior"
    } else {
      onLocation[i] <- "otherCampus"
    } 
  } else {
    onLocation[i] <- "offCampus"
  }
}
summary(data.frame(onLocation))

accessLocation <- data.frame(onLocation)

ezproxyData$accessLocation <- accessLocation

```

```{r, durationByLocationsTime}
#run ezyproxyPrelim first to get vectos


library(rpart)
tree1 <- rpart((endTimes-startTimes)~ezproxyData$Campus + ezproxyData$accessLocation[,1] + ezproxyData$StartTime)

printcp(tree1) # display the results 
plotcp(tree1) # visualize cross-validation results 
summary(tree1) # detailed summary of splits

# create additional plots 
par(mfrow=c(1,2)) # two plots on one page 
rsq.rpart(tree1) # visualize cross-validation results  	

# plot tree 
plot(tree1, uniform=TRUE, main="Regression Tree for Duration ")
text(tree1, use.n=TRUE, all=TRUE, cex=.8)

# create attractive postcript plot of tree 
#post(tree1, title = "Regression Tree for Duration ")
```

```{r, durationByLocations}

test2 <- anova(lm((endTimes-startTimes)~ezproxyData$Campus + ezproxyData$accessLocation[,1]))

tree2 <- rpart((endTimes-startTimes)~ezproxyData$Campus + ezproxyData$accessLocation[,1])

printcp(tree2) # display the results 
plotcp(tree2) # visualize cross-validation results 
summary(tree2) # detailed summary of splits

# create additional plots 
rsq.rpart(tree2) # visualize cross-validation results  	

# plot tree 
plot(tree2, uniform=TRUE, main="Regression Tree for Duration ")
text(tree2, use.n=TRUE, all=TRUE, cex=.8)



test2 <- aov((endTimes-startTimes)~ezproxyData$Campus + ezproxyData$accessLocation[,1])
summary(test2)
plot(test2$residuals~test2$fitted.values)
plot((endTimes-startTimes)~ezproxyData$Campus + ezproxyData$accessLocation[,1])


```


```{r, timesByLocations}

test3 <- anova(lm(startTimes~ezproxyData$Campus + ezproxyData$accessLocation[,1]))

tree3 <- rpart(startTimes~ezproxyData$Campus + ezproxyData$accessLocation[,1])


printcp(tree3) # display the results 
plotcp(tree3) # visualize cross-validation results 
summary(tree3) # detailed summary of splits

# create additional plots 
rsq.rpart(tree3) # visualize cross-validation results  	

# plot tree 
plot(tree3, uniform=TRUE, main="Regression Tree for StartTime ")
text(tree3, use.n=TRUE, all=TRUE, cex=.8)


```

```{r, locations}

tbl <- table(ezproxyData$accessLocation[,1],ezproxyData$Campus) 

test4 <- chisq.test(tbl)

barplot(tbl)

barplot(tbl, legend.text = TRUE, col = c("blue", "red", "green", "purple", "orange", "black", "pink", "white", "turquoise4", "maroon", "darkolivegreen4", "goldenrod3", "deeppink2", "steelblue3"))

barplot(rowSums(tbl, na.rm = FALSE, dims = 1))


```


```{r}
homeHits <- c(1347+ 15, 3581, 2631, 917, 142, 1253, 1160, 11362, 993)

offCampus <- c(27526+ 8, 5332, 683, 1453, 259, 6259, 4831, 7677, 4031)

totalHits <- c(36060+23,15114,4209,7316, 500,9985, 12970,22509,12000 )

differntCampus <- totalHits - offCampus - homeHits #anything on a campus that is not home


onOffTbl <- rbind(offCampus, differntCampus, homeHits)

barplot(onOffTbl, legend.text = c("Off Campus", "Different Campus", "Home Campus"), col =  c("darkolivegreen4", "goldenrod3", "steelblue3"))

```